# Generated by Django 2.1.7 on 2019-03-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[('2010', 2010), ('2011', 2011), ('2012', 2012), ('2013', 2013), ('2014', 2014), ('2015', 2015), ('2016', 2016), ('2017', 2017), ('2018', 2018), ('2019', 2019)])),
                ('graph', models.CharField(choices=[('A', 'Autors'), ('C', 'Citations')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GraphViz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='catalog/Graphs')),
                ('title', models.CharField(help_text='Year,, type', max_length=40)),
            ],
        ),
    ]
